import type { AttachmentFacts, TriageRequest } from './api'

export const MAX_FILES = 3
export const MAX_BYTES = 5 * 1024 * 1024
export const ACCEPT = 'image/png,image/jpeg,image/gif,image/webp,application/pdf'

// Fictional sample attachments served from /samples (generated by tools/samples).
export const SAMPLES = [
  { label: 'Scanner screenshot', file: 'scanner-screen.png', type: 'image/png' },
  { label: 'VPN error dialog', file: 'vpn-error.png', type: 'image/png' },
  { label: 'Customer email (PDF)', file: 'customer-email.pdf', type: 'application/pdf' },
] as const

// Adds files to the selection, skipping duplicates by name. Returns an error for the first
// file that can't be added; the server re-checks everything by content.
export function addFiles(current: File[], incoming: File[]): { files: File[]; error?: string } {
  const files = [...current]
  for (const f of incoming) {
    if (files.some((x) => x.name === f.name)) continue
    if (files.length >= MAX_FILES) return { files, error: `Attach at most ${MAX_FILES} files.` }
    if (f.size > MAX_BYTES) return { files, error: `${f.name} is larger than 5 MB.` }
    if (!ACCEPT.split(',').includes(f.type)) return { files, error: `${f.name} isn't an image or PDF.` }
    files.push(f)
  }
  return { files }
}

// What the dispatcher's ticket becomes after accepting the attachment facts: keep a title
// they typed, and append what the attachments add to the description.
export function applyFacts(ticket: TriageRequest, facts: AttachmentFacts): TriageRequest {
  const addendum = facts.description_addendum.trim()
  const description = [ticket.description.trim(), addendum && `From attachments: ${addendum}`]
    .filter(Boolean)
    .join('\n\n')
  return {
    short_description: ticket.short_description.trim() || facts.suggested_short_description.slice(0, 200),
    description: description.slice(0, 4000),
  }
}
